import{a as E,S as I,i as a}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const q="48284605-8cfffb6b97886c5ff39067830",B="https://pixabay.com/api/";async function p(t,o=1,s=15){const i=`${B}?key=${q}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${s}`,{data:e}=await E.get(i);if(!e.hits.length)throw new Error("No images found");return e}const h=document.querySelector(".gallery"),l=document.querySelector(".loader"),m=document.querySelector(".load-more");function y(t,o,s,i){if(t.length===0)g();else{const e=t.map(({webformatURL:r,largeImageURL:c,tags:v,likes:$,views:S,comments:_,downloads:P})=>`
      <a href="${c}" class="gallery__item">
        <div class="photo-card">
          <img src="${r}" alt="${v}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${$}</p>
            <p class="info-item"><b>Views:</b> ${S}</p>
            <p class="info-item"><b>Comments:</b> ${_}</p>
            <p class="info-item"><b>Downloads:</b> ${P}</p>
          </div>
        </div>
      </a>
    `).join("");h.insertAdjacentHTML("beforeend",e),s*i<o?O():g()}}function M(){h.innerHTML="",g()}function L(){l.classList.remove("hidden"),l.classList.add("visible"),l.classList.add("animate__animated","animate__fadeIn")}function b(){setTimeout(()=>{l.classList.add("hidden"),l.classList.remove("animate__fadeIn")},500)}function O(){m.classList.remove("hidden"),m.classList.add("visible")}function g(){m.classList.add("hidden")}function H(){const{height:t}=h.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}const N=document.querySelector("#search-form"),T=document.querySelector(".load-more");let n=1,u="",d=0;const f=15,w=new I(".gallery a");N.addEventListener("submit",async t=>{if(t.preventDefault(),u=t.target.elements.searchQuery.value.trim(),!u){a.warning({title:"Warning",message:"Please enter a search term!"});return}M(),n=1;try{L();const{hits:o,totalHits:s}=await p(u,n,f);if(d=s,!o.length){a.error({title:"Error",message:"No images found. Try again!"});return}y(o,d,n,f),w.refresh(),a.success({title:"Success",message:`Found ${d} images!`})}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{b()}});T.addEventListener("click",async()=>{n+=1;try{L();const{hits:t}=await p(u,n,f);y(t,d,n,f),w.refresh(),H(),n*f>=d&&a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{b()}});
//# sourceMappingURL=index.js.map
